import { RuleDefinition } from '../types/rules';

export const STANDARD_RULES: Record<string, RuleDefinition> = {
  // --- SECURITY ---
  'SEC-SQLI-001': {
    id: 'SEC-SQLI-001',
    name: 'SQL Injection Vulnerability',
    category: 'SECURITY',
    severity: 'CRITICAL',
    description: 'Dynamic SQL query built with unescaped string concatenation or formatting allows arbitrary query execution.',
    explanation: 'Unsanitized input allows an attacker to manipulate the structure of the executed SQL query, leading to unauthorized data extraction, modification, or full database takeover.',
    impact: 'Full database breach, data loss, elevation of privileges, or remote code execution via database extensions.',
    recommendation: 'Use parameterized queries, prepared statements, or ORM parameter binding instead of string concatenation.',
    cwe: 'CWE-89',
    owaspCategory: 'A03:2021-Injection',
    languages: ['javascript', 'typescript', 'python', 'java', 'php', 'csharp', 'go', 'ruby'],
    tags: ['owasp', 'cwe-89', 'injection', 'database'],
    effort: '20 minutes',
  },
  'SEC-XSS-001': {
    id: 'SEC-XSS-001',
    name: 'Cross-Site Scripting (XSS)',
    category: 'SECURITY',
    severity: 'HIGH',
    description: 'Unsanitized user-controlled input rendered directly into the DOM or HTML response allows script injection.',
    explanation: 'Direct insertion of untrusted data into HTML contexts (such as innerHTML, dangerouslySetInnerHTML, v-html) executes arbitrary scripts in the victim browser.',
    impact: 'Session hijacking, theft of authentication tokens/cookies, credential harvesting, defacement.',
    recommendation: 'Sanitize HTML with DOMPurify, use framework-native text interpolation, or encode output before rendering.',
    cwe: 'CWE-79',
    owaspCategory: 'A03:2021-Injection',
    languages: ['javascript', 'typescript', 'html', 'php', 'python'],
    tags: ['owasp', 'cwe-79', 'xss', 'frontend'],
    effort: '15 minutes',
  },
  'SEC-SECRET-001': {
    id: 'SEC-SECRET-001',
    name: 'Hardcoded Secret / Credential Leak',
    category: 'SECURITY',
    severity: 'CRITICAL',
    description: 'High-entropy credential, API token, private key, or password found hardcoded in source files.',
    explanation: 'Committing raw secrets into source code allows anyone with repository access (or historical git logs) to impersonate service credentials.',
    impact: 'Cloud account takeover, database exposure, unauthorized API abuse, lateral movement in corporate infrastructure.',
    recommendation: 'Store sensitive secrets in environment variables or cloud secret managers (e.g. AWS Secrets Manager, HashiCorp Vault).',
    cwe: 'CWE-798',
    owaspCategory: 'A07:2021-Identification and Authentication Failures',
    languages: ['all'],
    tags: ['secrets', 'credentials', 'cwe-798'],
    effort: '10 minutes',
  },
  'SEC-CMDI-001': {
    id: 'SEC-CMDI-001',
    name: 'Command Injection Vulnerability',
    category: 'SECURITY',
    severity: 'CRITICAL',
    description: 'Operating system command executed using dynamic string concatenation with untrusted input.',
    explanation: 'Calling OS shell functions like exec, system, or subprocess with shell=True and user parameters enables shell meta-character exploitation (`;`, `&&`, `|`).',
    impact: 'Complete server compromise, reverse shell creation, lateral network penetration.',
    recommendation: 'Use command execution APIs with explicit argument arrays (e.g. execFile or subprocess with shell=False) without invoking shell interpreters.',
    cwe: 'CWE-78',
    owaspCategory: 'A03:2021-Injection',
    languages: ['javascript', 'typescript', 'python', 'java', 'php', 'csharp', 'go', 'ruby'],
    tags: ['command-injection', 'cwe-78', 'rce'],
    effort: '30 minutes',
  },
  'SEC-SSRF-001': {
    id: 'SEC-SSRF-001',
    name: 'Server-Side Request Forgery (SSRF)',
    category: 'SECURITY',
    severity: 'HIGH',
    description: 'Server makes an outbound HTTP request using a user-supplied target address without strict whitelist validation.',
    explanation: 'Attackers can supply internal IP ranges (127.0.0.1, 169.254.169.254 metadata endpoint) to access private microservices and cloud instance credentials.',
    impact: 'Cloud IAM credential exfiltration from metadata services, internal network port scanning, bypassing firewalls.',
    recommendation: 'Validate and whitelist target hosts, block internal loopback/private CIDR ranges, and avoid following redirects to private addresses.',
    cwe: 'CWE-918',
    owaspCategory: 'A10:2021-Server-Side Request Forgery',
    languages: ['javascript', 'typescript', 'python', 'java', 'go', 'php', 'csharp'],
    tags: ['ssrf', 'cwe-918', 'network'],
    effort: '25 minutes',
  },
  'SEC-PATH-001': {
    id: 'SEC-PATH-001',
    name: 'Path Traversal Vulnerability',
    category: 'SECURITY',
    severity: 'HIGH',
    description: 'File system operations performed using unsanitized user-provided file paths containing directory traversal characters.',
    explanation: 'Lack of canonicalization allows parameters with `../` or `..\\` sequences to access arbitrary files outside the intended root directory.',
    impact: 'Unauthorized file disclosure (e.g. /etc/passwd, configuration files with private keys), or arbitrary file overwrite.',
    recommendation: 'Use path normalization (e.g. path.resolve), ensure resolved path starts with intended root prefix, or use an identifier lookup table.',
    cwe: 'CWE-22',
    owaspCategory: 'A01:2021-Broken Access Control',
    languages: ['javascript', 'typescript', 'python', 'java', 'go', 'php', 'csharp'],
    tags: ['path-traversal', 'cwe-22', 'filesystem'],
    effort: '15 minutes',
  },
  'SEC-CRYPTO-001': {
    id: 'SEC-CRYPTO-001',
    name: 'Use of Broken or Weak Cryptographic Algorithm',
    category: 'SECURITY',
    severity: 'MEDIUM',
    description: 'Cryptographic operations using broken algorithms like MD5, SHA-1, DES, or predictable pseudo-random number generators.',
    explanation: 'Legacy hash algorithms suffer from collision attacks and rainbow table precomputation, rendering them unsafe for digital signatures or passwords.',
    impact: 'Collision exploitation, signature forgery, password hash cracking.',
    recommendation: 'Use modern cryptographic hashing (SHA-256 / SHA-3) for integrity, and Argon2id or bcrypt for password storage.',
    cwe: 'CWE-327',
    owaspCategory: 'A02:2021-Cryptographic Failures',
    languages: ['javascript', 'typescript', 'python', 'java', 'go', 'php', 'csharp'],
    tags: ['crypto', 'cwe-327', 'hash'],
    effort: '20 minutes',
  },
  'SEC-DESER-001': {
    id: 'SEC-DESER-001',
    name: 'Unsafe Object Deserialization',
    category: 'SECURITY',
    severity: 'CRITICAL',
    description: 'Deserializing untrusted data with unrestricted object instantiation mechanisms like Python pickle, Java ObjectInputStream, or PHP unserialize.',
    explanation: 'Untrusted byte streams can instantiate gadget chains that invoke arbitrary system methods upon deserialization.',
    impact: 'Remote Code Execution (RCE) on the server without authentication.',
    recommendation: 'Use safe data exchange formats such as JSON or Protocol Buffers, or cryptographically sign and verify payloads before deserialization.',
    cwe: 'CWE-502',
    owaspCategory: 'A08:2021-Software and Data Integrity Failures',
    languages: ['python', 'java', 'php', 'csharp', 'ruby'],
    tags: ['deserialization', 'cwe-502', 'rce'],
    effort: '40 minutes',
  },

  // --- CODE QUALITY & COMPLEXITY ---
  'QUAL-GODCLASS-001': {
    id: 'QUAL-GODCLASS-001',
    name: 'God Class Anti-Pattern',
    category: 'CODE_QUALITY',
    severity: 'HIGH',
    description: 'Class exceeds excessive line count (>500 LOC) and handles too many distinct responsibilities.',
    explanation: 'Violates Single Responsibility Principle (SRP). Makes code fragile, tightly coupled, and difficult to test or maintain.',
    impact: 'High defect rates during modifications, complex merge conflicts, steep developer onboarding curve.',
    recommendation: 'Refactor into smaller, focused domain classes or service delegates following SRP and composition.',
    cwe: 'CWE-1061',
    languages: ['all'],
    tags: ['architecture', 'srp', 'code-smell', 'refactoring'],
    effort: '2 hours',
  },
  'QUAL-LONGMETHOD-001': {
    id: 'QUAL-LONGMETHOD-001',
    name: 'Excessive Method Length',
    category: 'CODE_QUALITY',
    severity: 'MEDIUM',
    description: 'Method or function exceeds recommended maximum length (>60 lines).',
    explanation: 'Long methods often perform multiple tasks, contain mixed levels of abstraction, and hide edge cases.',
    impact: 'Reduced readability, hard-to-write unit tests, duplicate logic.',
    recommendation: 'Extract sub-operations into private helper methods with descriptive names.',
    cwe: 'CWE-1061',
    languages: ['all'],
    tags: ['clean-code', 'refactoring'],
    effort: '30 minutes',
  },
  'QUAL-DEEPNEST-001': {
    id: 'QUAL-DEEPNEST-001',
    name: 'Deep Control Flow Nesting',
    category: 'COMPLEXITY',
    severity: 'MEDIUM',
    description: 'Block nesting depth exceeds 4 levels of nested if/for/while statements.',
    explanation: 'Deep nesting exponentially increases the mental overhead required to trace execution paths and causes cognitive fatigue.',
    impact: 'Increased bug likelihood, missed branch conditions, high cognitive complexity.',
    recommendation: 'Apply guard clauses, early returns, or extract inner logic into smaller functions.',
    languages: ['all'],
    tags: ['complexity', 'cognitive-complexity'],
    effort: '20 minutes',
  },
  'QUAL-DEADCODE-001': {
    id: 'QUAL-DEADCODE-001',
    name: 'Unreachable or Dead Code Detected',
    category: 'CODE_QUALITY',
    severity: 'LOW',
    description: 'Code blocks following return/throw statements or unused private functions that can never be executed.',
    explanation: 'Dead code clutters the codebase, misleads developers, and bloats bundle size.',
    impact: 'Codebase bloat and cognitive distraction.',
    recommendation: 'Remove unused code blocks and unreferenced symbols.',
    cwe: 'CWE-561',
    languages: ['all'],
    tags: ['cleanup', 'dead-code'],
    effort: '10 minutes',
  },

  // --- PERFORMANCE ---
  'PERF-NPLUS1-001': {
    id: 'PERF-NPLUS1-001',
    name: 'N+1 Database Query Pattern in Loop',
    category: 'PERFORMANCE',
    severity: 'HIGH',
    description: 'Database query executed inside a loop over a collection of records.',
    explanation: 'For a collection of N items, N individual database round-trips are initiated instead of a single batched join or `IN` query.',
    impact: 'Severe latency degradation under load, connection pool exhaustion, database CPU spikes.',
    recommendation: 'Use eager loading (e.g. `include`, `select_related`, `joinFetch`) or batch query IDs using `WHERE id IN (...)`.',
    languages: ['javascript', 'typescript', 'python', 'java', 'php', 'csharp', 'ruby', 'go'],
    tags: ['database', 'n+1', 'performance', 'latency'],
    effort: '30 minutes',
  },
  'PERF-SYNCIO-001': {
    id: 'PERF-SYNCIO-001',
    name: 'Blocking Synchronous I/O in Async Context',
    category: 'PERFORMANCE',
    severity: 'HIGH',
    description: 'Synchronous file/network operations (e.g. `fs.readFileSync`, `time.sleep`) executed on an async event loop.',
    explanation: 'Synchronous calls block the entire runtime event thread, preventing concurrent user requests from being processed.',
    impact: 'Throughput bottleneck, increased p99 latency, request timeouts under load.',
    recommendation: 'Replace synchronous APIs with non-blocking async/await equivalents (e.g. `fs.promises.readFile`).',
    languages: ['javascript', 'typescript', 'python'],
    tags: ['event-loop', 'async', 'performance'],
    effort: '15 minutes',
  },

  // --- ARCHITECTURE ---
  'ARCH-CIRCULAR-001': {
    id: 'ARCH-CIRCULAR-001',
    name: 'Circular Module Dependency',
    category: 'ARCHITECTURE',
    severity: 'HIGH',
    description: 'Modules import each other directly or transitively in a closed dependency loop.',
    explanation: 'Circular dependencies cause runtime initialization errors (undefined module exports), hinder tree-shaking, and prevent decoupling.',
    impact: 'Unpredictable startup crashes, memory leaks, untestable tangled modules.',
    recommendation: 'Extract shared interfaces/types or data models into a separate common module or apply dependency inversion.',
    languages: ['javascript', 'typescript', 'python', 'go', 'java', 'csharp'],
    tags: ['architecture', 'coupling', 'circular-dependency'],
    effort: '45 minutes',
  },

  // --- DOCKER & KUBERNETES ---
  'DOCK-ROOT-001': {
    id: 'DOCK-ROOT-001',
    name: 'Container Runs as Root User',
    category: 'DOCKER',
    severity: 'HIGH',
    description: 'Dockerfile does not specify a non-root USER directive.',
    explanation: 'Running container processes as root increases the blast radius if a container breakout vulnerability is exploited.',
    impact: 'Host system compromise upon container escape.',
    recommendation: 'Add a dedicated unprivileged user and switch to it using `USER <username>` before the entrypoint.',
    cwe: 'CWE-250',
    languages: ['dockerfile'],
    tags: ['docker', 'container-security', 'least-privilege'],
    effort: '10 minutes',
  },
  'K8S-PRIVILEGED-001': {
    id: 'K8S-PRIVILEGED-001',
    name: 'Kubernetes Pod Configured in Privileged Mode',
    category: 'KUBERNETES',
    severity: 'CRITICAL',
    description: 'Container securityContext has `privileged: true`.',
    explanation: 'Privileged containers gain full capabilities of the host kernel, bypassing container isolation boundaries.',
    impact: 'Direct host node takeover and cluster-wide privilege escalation.',
    recommendation: 'Set `privileged: false` and grant only specific required Linux capabilities (e.g. `NET_BIND_SERVICE`).',
    languages: ['yaml'],
    tags: ['k8s', 'security-context', 'privilege-escalation'],
    effort: '15 minutes',
  },
};
